name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      foo:
        description: bar
        required: true
        type: environment
      bar:
        description: foo
        required: true
        default: test-samrat
        type: choice
        options:
          - samrat
          - not-samrat

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DONE foo has ${{ github.event.inputs.foo}} and bar has ${{ github.event.inputs.bar }}"

